### ISSUE TITLE
how does this to be used?

### ISSUE THREAD

**Issue by nosyguy** [jellyfin/jellyfin-chromecast#466]
noob here so apology in advance.
How can I use this script? is this a plugin to be added to an existing jellyfin server? or it's a version of the server that can work with chromecast? how can I use this?
I do appreciate any help

thank youuu

**Comment by nielsvanvelzen** [comment]
The cast integration is built-in with the Jellyfin provides web client. You can use the "play on" menu on the top-right corner and select "Google Cast" to start casting.

This repository is for our official cast receiver, which is automatically used.

**Comment by nosyguy** [comment]
thank you so much for getting back to me.
As I said I am a noob and I really appreciate your help. 
My apologizes but I didn't quite understand your answer. Can you please elaborate a bit? is this included in the default Jellyfin web client? I ask since when I click on "play on" says "(Google Cast Unsupported)". 
I still don't know how I can use this script to be able to cast on Chromecast.
p.s: I have already blocked google dns on my router to make it won't cause an issue.

I have hit brick wall and your help could save my sanity at this point lol

**Comment by nielsvanvelzen** [comment]
The chromecast receiver is not shipped with jellyfin-web. It's hosted separately and can thus be updated independently. To use chromecasts in Jellyfin you need a compatible client this can be:

1) The mobile Android app (proprietary version, so not installed via F-Droid)
2) jellyfin-web in a compatible browser (chromium based like Chrome/Edge/Vivaldi)

If you need help getting casting to work I'd suggest using our [forum or chat](https://jellyfin.org/contact/) options.

**Comment by nosyguy** [comment]
Thank you so much. I have a much better understanding of it now. Just one last huge favour, how can I add this to jellyfin-web?

**Comment by nielsvanvelzen** [comment]
You don't add it to jellyfin-web

**Comment by nosyguy** [comment]
I still haven't been able to figure out how/where use this script :'(

**Comment by nielsvanvelzen** [comment]
You don't need to add the receiver to your server. Support for self-hosting it will come with 10.9 (although you should not need to do this).

**Comment by tim-vk** [comment]
Is it maybe a good idea to add this description to the README?

Things that i'm (as a semi-technical user) am kind of looking for is:

What is this repository:
"Cast integration deployed with your jellyfin instance used when casting to your chromecast"

When do I have to be near this repository:
(my assumption): Anything related to casting. If a issue occurs in any other client & when casting then it should not be an issue here.

What version am I using at the moment? (since it is seperate app: how do i find its specific version number?).

For testing: Add a description that points to the stable/unstable setting & what it exactly does (since i'm still kind of unsure about that). (maybe nice to have: add the version/hash here, but that's unrelated to just a README).

**Comment by nielsvanvelzen** [comment]
A better README would definitely be nice to have, feel free to open a pull request with your suggested changes.

**Comment by tim-vk** [comment]
I've created a pull request. Did still have some questions but we can continue the discussion there:
#537
