### ISSUE TITLE
Not able to DirectPlay HEVC/H265 on Chromecast Ultra

### ISSUE THREAD

**Issue by ownbee** [jellyfin/jellyfin-chromecast#98]
**Describe the bug**
Chomecast Ultra should support `hevc` and `aac` so I have converted some 4K movies to that since my server isn't a monster and would like to direct play these large movies. Problem is Jellyfin always starts to transcode the movie anyway. I only have mkv movies to try with but I have read it should not be a problem if the codec is correct on streams inside it.

It looks like hevc isn't in the "playback profile" jellyfin use when casting to Chromecast Ultra. Is there a workaround for this? Can I somehow try configure my way around this? I have not found any guide on how this works.

The only player I have successfully getting hevc direct playback to work with is `jellyfin-mpv-shim`. Web-browser built-in player and Chromecast always "fail" for me.

**System (please complete the following information):**
 - OS: Linux
 - Virtualization: Docker
 - Clients: Browser, Android
 - Browser: Chrome
 - Jellyfin Version: 10.7.0-rc1
 - Installed Plugins: none
 - Reverse Proxy: nginx]
 - Networking: Bridge/NAT
 - Storage: local

**To Reproduce**

1. Connect to Chromecast Ultra in Chrome or Android app.
2. Play a movie with HEVC and AAC streams
3. Jellyfin starts to transcode

**Expected behavior**
Direct replay or direct stream (don't know the difference) and no transcoding.

**Logs**
`[2020-12-13 21:23:33.364 +00:00] [INF] [113] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: "Unknown Profile", No video direct play profiles found for "/data/media/movies/The Prestige (2006)/movie.mkv" with codec "hevc"`

**Comment by idittansikte** [comment]
After some more investigation, it seem to be ac3 and mkv that is not allowed by chromecast receiver and thus forcing the server to transcode if content have any of this. I have most of my 4k movies in mkv container and AC3 audio, which is common I guess, which makes this annoying. Is this something that is worked on?

I am currently testing with the receiver code which I have managed to setup in a debug environement using a chromecast ultra. My findings so far is that AC3 is hard-disabled with a comment that it did not work on some setup and therefore disabled. I think I know why. `castContext.canDisplayType('video/mp4', 'ac-3')`, which was used to check if AC3 was supported only checks that the chromecast itself has support for it and not if the TV has it. Since only AC3 passthrough is supported by some chromecast models, the cast will fail when passthrough is happening and the TV cant receive it. You can check the TV dolby support with `context.getDeviceCapabilities()`, and you can also force enable dolby passthough on the chromecast in Google Home Chromecast settings (which will result in no audio if instead of ERROR which TV lacking dolby support).

I have also added a mkv profile for direct play and I have no problem with that itself so far. I am currently struggling with not being able to select an other audio stream than default/main. To be continued...

**Comment by Artiume** [comment]
Something else you could test is fmp4 streaming, this should allow Direct Streaming with hevc. It doesn't fix the issue but it should allow the server to not convert the hevc to h264 when the audio needs to be converted. You can select it from your user profile > playback, this is a new feature for 10.7

**Comment by idittansikte** [comment]
@Artiume, Thanks for the tip, I've seen this option and tried it both checked and unchecked but I have not figured out what it means to turn it on yet. I am not even sure if HLS is used or not at all times when direct playing/streaming but I will keep digging a bit more. There are so many switches, controllers and back and forth communication making it hard for me to figure out the code but I make progress at least.

Would have been great with more clear log messages/summary that states the paths taken a bit clearer. The receiver is also a bit of a black box now with very limited reporting (to clients). This makes it very hard to understand why some choices are made related to transcoding and choice of protocol and audio/video/sub streams. You basically need to setup chromecast debugging env to figure out why a particular file is not working (as one expect). Could be enough with a detail explanation in wiki about how things work.

**Comment by Artiume** [comment]
So Direct Play should just be the server giving the client the file as is, no hls involved. If hls is involved, that'll be done via ffmpeg and I always look at the ffmpeg logs to check the behavior. I don't have a cc yet so I can't help much there

**Comment by hawken93** [comment]
Hi,

At the moment the chromecast only really advertises HLS. fmp4 is apparently the way to go to get HEVC, although it will still remux.

As for the sound, I have an issue open with google because the chromecast somehow always errors out on ac3/eac3, even when the system supports it. >2ch aac is also not supported. This limits us to stereo for the moment.

Which brings me to my testing with canDisplayType. Firstly, the API documentation encourages developers to specifically use this check before playing back ac3/eac3 content. Secondly I have verified that this check returns false if the chromecast is in stereo only mode, or if it's in auto but it did not detect ac3-capable equipment.  It returns true when the equipment supports it or if it's set to force it on. So in this regard I don't think getDeviceProfile will do anything differently.

It was decided that mkv would no longer be sent to the device because the device only supports a subset and this may work or fail based on bad luck with a particular file.

I'm working on backporting to the old receiver API to be able to compare how they perform. I'm hoping that this will either prove my hypothesis that CAF behaves really badly, or it will help uncover problems that cause CAF to underperform in this app.

As for logs, I'm blaming google because all the logging is done to the console since it's a web browser, and you have to pay them for access to the developer console where you can register a testing app. Doing so will let you connect to the receiver and read those logs. It's really annoying but I don't think web browsers have any easy facilities for redirecting those logs. If they did, the server is the place I think it would be appropriate to push those logs.

**Comment by idittansikte** [comment]
I bought the developer console (it was just 5 dollars so I thought it wasn't that bad but I agree with you) and set up a local server for the receiver. I added some extended console logging around ac3/eac3 and did some tests. If I set the chromecast audio to "auto" mode and play ac3 stream, the chromecast error-out but if I set it to the "surround mode" I get it to play with no sound (my current setup only have stereo, I will test in dolby system later). Now if I check canDisplayType, it say it can display ac3 and eac3 but the getDeviceCapabilities() say dolby vision is not supported. Therefore I did the conclusion that canDisplayType() only tells what the particular chromecast is capable of and not the chromecast + device.

Okey interesting regarding the mkv, isn't that just a flat container? I've read the internet and some places state that mkv is fine as long as the streams in it are chromecast-compatable (which could be hard to tell sometimes apparently). 

I read in some google problem report thread last night on my phone (did not save the link :/) that >2ch aac is supported lately but I don't remember the details.

Regarding streaming logs, [Custom Messages](https://developers.google.com/cast/docs/web_receiver/core_features#custom_messages) could be something to use. I mean it would be nice to all ppl that would like some extended logging without having to buy Chromecast developer console and setup a server serving the receiver app. You could also use the TV screen to display errors and problems. A small thing like "Chromecast was given a stream with incompatable format" (just a bad example) on the screen would help a lot to understand that there is something wrong with the stream and not jellyfin server crashing. As I said, its a black box now and it could be improved, but as always, time is sometimes hard to come by.

**Comment by hawken93** [comment]
Dolby Vision is not the same as ac3/eac3. Dolby Vision, or DV, is a HDR video format..

**Comment by hawken93** [comment]
I agree that some logs could be sent, but my worry is that without the full debug log it's hard for anyone to really provide enough feedback to get a good understanding of what happened. On screen error messages should be a thing though. :)

**Comment by hawken93** [comment]
Also see https://issuetracker.google.com/issues/174837344
This is the issue I opened with HLS+AC3 and HLS+EAC3

**Comment by hawken93** [comment]
I think it would be most productive if this issue is used to report the fact that hevc support is not implemented in jellyfin-chromecast.

Even if the audio and container are still transcoded/remuxed, copying the video track will save you a massive amount of cpu and probably work.


In addition to enabling it server side on 10.7, I believe jellyfin-chromecast needs at least a small patch to advertise support for fmp4 and hevc back to the server. We are still unsure if fmp4 will work with chromecast, but it's worth trying. I think it will work. If we somehow got rid of HLS it might also work around the ac3 issue.

**Comment by hawken93** [comment]
https://stackoverflow.com/questions/63172210/chromecast-hls-unable-to-derive-timescale/63172539#63172539
just leaving this here for whoever is going to look at playing back fmp4

**Comment by idittansikte** [comment]
@hawken93, firstly, thanks a lot for your explanation! Would be good if this information could be in the documentation (maybe a whole chromecast section with tips and tricks that we've learned) since not everybody have a monster PC to do all transcoding they want on the fly for all users. You'll need to know what's supposed to work and what's not working (and why so ppl like me don't get grumpy) so that you can tweak your media the best way without loosing all the goodies.

I mixed up Dolby Vision with Dolby Digital, my bad!

Copying the video track would be fine for me, but as it is now, always transcode hevc to h264 seem like a ridiculous waste of resources if you have a chromecast ultra. And yes I've seen manifest 411 a couple of times :).

I'll look more into fmp4 and see if I can get it working.

**Comment by Artiume** [comment]
could add the chromecast to this page 👀

https://jellyfin.org/docs/general/clients/codec-support.html

**Comment by hawken93** [comment]
@idittansikte Much of what is explained here is in @YouKnowBlom s list of things to fix before nightly becomes stable. But I agree with @Artiume that it could be noted in that page what chromecast stable and chromecast nightly support at the moment.

My impression has been that the stable receiver is still around because this nightly is still just not good yet.

The challenges I'm facing with it is the ones we have talked about here, but also that on my gen2 and gen3, it just seems to choke itself for some reason. In theory we should support everything on googles official support list, but the exceptions to that can be seen in the issues here. I also have some issues with playback randomly erroring out. This is all very irritating and due to all the things being wrong, we need to make sure to make one issue per item so that we don't overwhelm ourselves.

On the positive side I think nightly is now able to play more media than before because of small bugfixes and by avoiding ac3 until it actually works. For your everyday use I would recommend using the stable receiver on 10.6. It's not ideal, but it direct plays a lot more, not convinced about hevc support but ac3 works.

**Comment by hawken93** [comment]
This issue has become very big now, I do like your suggestion about some logging that the user can see either OSD, via a server API or communicated to the sender. If you would like, feel free to make a feature request issue for that :+1:

**Comment by hawken93** [comment]
Also see https://github.com/jellyfin/jellyfin-chromecast/issues/76 for fmp4

**Comment by hawken93** [comment]
https://github.com/jellyfin/jellyfin-chromecast/pull/100

I'm re-enabling mkv even though we know that some mkv files will fail, because currently nightly is just not good with HLS. I think there's an upstream problem which we will look closer at. This also enables ac3 and eac3 and I think also hevc over mkv.

Feel free to compile it and try it :)

This is just a band aid however, seeing if we can fix the HLS support would be best, and also enabling fmp4.

**Comment by idittansikte** [comment]
I've made a few tries in the morning with ac-3 disabled (in receiver code) playing H265/AC3 on a Chromecast gen 1 or 2 (don't know exactly) and get manifest 411 error. The ffmeg is not even started.

Manifest sent by jellyfin:
`
#EXTM3U
#EXT-X-STREAM-INF:BANDWIDTH=22053756,AVERAGE-BANDWIDTH=22053756,VIDEO-RANGE=SDR,CODECS=\"avc1.640029,mp4a.40.2\",RESOLUTION=3840x1608,FRAME-RATE=23.976
main.m3u8?DeviceId=S3JvbWthc3RhcmVu&MediaSourceId=20bda828378da598fcaabcd08da551ef&Static=false&VideoCodec=h264&AudioCodec=aac,mp3&AudioStreamIndex=1&VideoBitrate=21669756&AudioBitrate=384000&MaxWidth=1920&PlaySessionId=1b781791ba844167be29d2bb9ec387b5&api_key=428429bce56e4538ac7ecba04e2015e0&SubtitleMethod=Encode&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=774eae2549d01e6a97967ece8aa1a2f8&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=False&h264-profile=high,main,baseline,constrainedbaseline&h264-level=41&TranscodeReasons=VideoCodecNotSupported
`
RESOLUTION=3840x1608 seems not right even though its "optimal resolution".


As for ac-3 enabled, you can configure the Chromecast in Google Home to only use stereo instead to "Detect automatically" canDisplayType does not return true on ec3/ac3. If this is advertised on jellyfin wiki, ppl can try for themself and set "stereo" if they have problems.

I'll try your commit asap!

**Comment by hawken93** [comment]
I know all this, we are having terrible luck with HLS. mkv is way better.

**Comment by hawken93** [comment]
Also does your chromecast look like a key or a hockey puck? That's the difference between gen1 and gen2 :)

**Comment by idittansikte** [comment]
Okay great! Do you mean mkv direct play?

I looks like a key so I guess gen1 then :).

**Comment by idittansikte** [comment]
@hawken93 I tried your PR without success. Played an mkv - hevc - ac3 movie with forced stereo which should trigger a http stream but instead jellyfin setups an HLS-TS stream which fails since hevc isn't supported in TS (if I've got it right).

**Comment by hawken93** [comment]
I've only made it go mkv for ac3 formats right now. So if you can, try enabling that

**Comment by idittansikte** [comment]
Alright, that is working.

I've a some 4k movies with AAC surround as default and stereo tracks as secondary. Problem is, I can't select "secondary" audio tacks when using direct play. I've tried removed the constraints on this in the receiver without success but I guess it's not supported right now. Do you know if there is a PR for this?

I also tried the same thing to enable fmp4 as #76 and played hevc/aac.surr but my CC Ultra froze 60 seconds in (after about 10 segements). But played nicely with sound before that. I had to also set `loadRequestData.media.hlsVideoSegmentFormat = cast.framework.messages.HlsVideoSegmentFormat.FMP4;` in order for it to work at all though.

**Comment by ownbee** [comment]
Closed this since it kinda works. The problem is not HEVC/H265 but other stuff (audio and mkv).
